In [1]:
from shapely.geometry import Point
import pandas as pd
import json
import requests
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster
from folium.plugins import FastMarkerCluster

In [2]:
counties = gpd.read_file('../data/usa_counties.geojson')
print(counties.crs)
counties

epsg:4326

,geo_point_2d,year,ste_code,ste_name,coty_code,coty_name,coty_area_code,coty_type,coty_name_long,coty_fp_code,coty_gnis_code,geometry
0,"{'lon': -93.99206370718835, 'lat': 40.35466873...",2022,[29],[Missouri],[29081],[Harrison],USA,county,[Harrison County],081,00758495,"POLYGON ((-94.23224 40.57190, -94.23235 40.565..."
1,"{'lon': -90.53771211550016, 'lat': 38.26100393...",2022,[29],[Missouri],[29099],[Jefferson],USA,county,[Jefferson County],099,00758504,"POLYGON ((-90.63998 38.07655, -90.63989 38.076..."
2,"{'lon': -94.33924648479106, 'lat': 36.90550895...",2022,[29],[Missouri],[29145],[Newton],USA,county,[Newton County],145,00758527,"POLYGON ((-94.05921 37.04813, -94.05967 37.048..."
3,"{'lon': -90.46142948091351, 'lat': 37.11263544...",2022,[29],[Missouri],[29223],[Wayne],USA,county,[Wayne County],223,00758564,"POLYGON ((-90.77955 37.05032, -90.76834 37.050..."
4,"{'lon': -115.4050804689004, 'lat': 48.54247976...",2022,[30],[Montana],[30053],[Lincoln],USA,county,[Lincoln County],053,01720038,"POLYGON ((-114.72705 49.00051, -114.75952 49.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...
3230,"{'lon': -91.408829118662, 'lat': 47.5232212915...",2022,[27],[Minnesota],[27075],[Lake],USA,county,[Lake County],075,00659484,"POLYGON ((-90.79519 47.24430, -90.80062 47.249..."
3231,"{'lon': -94.61303322931869, 'lat': 45.55213974...",2022,[27],[Minnesota],[27145],[Stearns],USA,county,[Stearns County],145,00659517,"POLYGON ((-95.13188 45.41249, -95.13173 45.412..."
3232,"{'lon': -89.8020061955374, 'lat': 33.769954007...",2022,[28],[Mississippi],[28043],[Grenada],USA,county,[Grenada County],043,00695746,"POLYGON ((-89.78689 33.67673, -89.78255 33.676..."
3233,"{'lon': -88.64115956577189, 'lat': 32.75455794...",2022,[28],[Mississippi],[28069],[Kemper],USA,county,[Kemper County],069,00695758,"POLYGON ((-88.34789 32.92908, -88.35697 32.928..."
3234,"{'lon': -88.48046704586976, 'lat': 33.89224179...",2022,[28],[Mississippi],[28095],[Monroe],USA,county,[Monroe County],095,00695771,"POLYGON ((-88.24892 33.74498, -88.24805 33.750..."

In [3]:
counties.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [4]:
counties.dtypes

geo_point_2d        object
year                object
ste_code            object
ste_name            object
coty_code           object
coty_name           object
coty_area_code      object
coty_type           object
coty_name_long      object
coty_fp_code        object
coty_gnis_code      object
geometry          geometry
dtype: object

In [9]:
counties['ste_name'].value_counts()

ste_name
[Texas]                                           254
[Georgia]                                         159
[Virginia]                                        133
[Kentucky]                                        120
[Missouri]                                        115
[Kansas]                                          105
[Illinois]                                        102
[North Carolina]                                  100
[Iowa]                                             99
[Tennessee]                                        95
[Nebraska]                                         93
[Indiana]                                          92
[Ohio]                                             88
[Minnesota]                                        87
[Michigan]                                         83
[Mississippi]                                      82
[Puerto Rico]                                      78
[Oklahoma]                                         77
[Arkansas]                                         75
[Wisconsin]                                        72
[Pennsylvania]                                     67
[Alabama]                                          67
[Florida]                                          67
[South Dakota]                                     66
[Louisiana]                                        64
[Colorado]                                         64
[New York]                                         62
[California]                                       58
[Montana]                                          56
[West Virginia]                                    55
[North Dakota]                                     53
[South Carolina]                                   46
[Idaho]                                            44
[Washington]                                       39
[Oregon]                                           36
[New Mexico]                                       33
[Alaska]                                           30
[Utah]                                             29
[Maryland]                                         24
[Wyoming]                                          23
[New Jersey]                                       21
[Nevada]                                           17
[Maine]                                            16
[Arizona]                                          15
[Vermont]                                          14
[Massachusetts]                                    14
[New Hampshire]                                    10
[Connecticut]                                       9
[American Samoa]                                    5
[Rhode Island]                                      5
[Hawaii]                                            5
[Commonwealth of the Northern Mariana Islands]      4
[United States Virgin Islands]                      3
[Delaware]                                          3
[District of Columbia]                              1
[Guam]                                              1
Name: count, dtype: int64

In [12]:
counties.ste_name = counties.ste_name.explode()
counties

,geo_point_2d,year,ste_code,ste_name,coty_code,coty_name,coty_area_code,coty_type,coty_name_long,coty_fp_code,coty_gnis_code,geometry
0,"{'lon': -93.99206370718835, 'lat': 40.35466873...",2022,[29],Missouri,[29081],[Harrison],USA,county,[Harrison County],081,00758495,"POLYGON ((-94.23224 40.57190, -94.23235 40.565..."
1,"{'lon': -90.53771211550016, 'lat': 38.26100393...",2022,[29],Missouri,[29099],[Jefferson],USA,county,[Jefferson County],099,00758504,"POLYGON ((-90.63998 38.07655, -90.63989 38.076..."
2,"{'lon': -94.33924648479106, 'lat': 36.90550895...",2022,[29],Missouri,[29145],[Newton],USA,county,[Newton County],145,00758527,"POLYGON ((-94.05921 37.04813, -94.05967 37.048..."
3,"{'lon': -90.46142948091351, 'lat': 37.11263544...",2022,[29],Missouri,[29223],[Wayne],USA,county,[Wayne County],223,00758564,"POLYGON ((-90.77955 37.05032, -90.76834 37.050..."
4,"{'lon': -115.4050804689004, 'lat': 48.54247976...",2022,[30],Montana,[30053],[Lincoln],USA,county,[Lincoln County],053,01720038,"POLYGON ((-114.72705 49.00051, -114.75952 49.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...
3230,"{'lon': -91.408829118662, 'lat': 47.5232212915...",2022,[27],Minnesota,[27075],[Lake],USA,county,[Lake County],075,00659484,"POLYGON ((-90.79519 47.24430, -90.80062 47.249..."
3231,"{'lon': -94.61303322931869, 'lat': 45.55213974...",2022,[27],Minnesota,[27145],[Stearns],USA,county,[Stearns County],145,00659517,"POLYGON ((-95.13188 45.41249, -95.13173 45.412..."
3232,"{'lon': -89.8020061955374, 'lat': 33.769954007...",2022,[28],Mississippi,[28043],[Grenada],USA,county,[Grenada County],043,00695746,"POLYGON ((-89.78689 33.67673, -89.78255 33.676..."
3233,"{'lon': -88.64115956577189, 'lat': 32.75455794...",2022,[28],Mississippi,[28069],[Kemper],USA,county,[Kemper County],069,00695758,"POLYGON ((-88.34789 32.92908, -88.35697 32.928..."
3234,"{'lon': -88.48046704586976, 'lat': 33.89224179...",2022,[28],Mississippi,[28095],[Monroe],USA,county,[Monroe County],095,00695771,"POLYGON ((-88.24892 33.74498, -88.24805 33.750..."

In [15]:
tn_counties = counties.loc[(counties['ste_name'] == 'Tennessee')]

In [16]:
tn_counties.coty_name_long = tn_counties.coty_name_long.explode()
tn_counties

C:\Users\oxyje\anaconda3\envs\geospatial_ds6\lib\site-packages\geopandas\geodataframe.py:1472: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,geo_point_2d,year,ste_code,ste_name,coty_code,coty_name,coty_area_code,coty_type,coty_name_long,coty_fp_code,coty_gnis_code,geometry
27,"{'lon': -86.45888596525718, 'lat': 35.51379812...",2022,[47],Tennessee,[47003],[Bedford],USA,county,Bedford County,003,01639723,"POLYGON ((-86.25759 35.41248, -86.25566 35.412..."
79,"{'lon': -83.52419219232492, 'lat': 35.78465550...",2022,[47],Tennessee,[47155],[Sevier],USA,county,Sevier County,155,01639789,"POLYGON ((-83.67330 36.03849, -83.67340 36.036..."
80,"{'lon': -86.46055276723207, 'lat': 36.46905126...",2022,[47],Tennessee,[47165],[Sumner],USA,county,Sumner County,165,01639794,"POLYGON ((-86.59436 36.24538, -86.59110 36.245..."
143,"{'lon': -89.28383568027076, 'lat': 35.58322202...",2022,[47],Tennessee,[47075],[Haywood],USA,county,Haywood County,075,01639753,"POLYGON ((-89.50212 35.58062, -89.50147 35.580..."
144,"{'lon': -87.85896668760574, 'lat': 35.64263441...",2022,[47],Tennessee,[47135],[Perry],USA,county,Perry County,135,01639781,"POLYGON ((-87.71676 35.83875, -87.72611 35.838..."
...,...,...,...,...,...,...,...,...,...,...,...,...
3058,"{'lon': -85.54385992722223, 'lat': 36.55115725...",2022,[47],Tennessee,[47027],[Clay],USA,county,Clay County,027,01648573,"POLYGON ((-85.78873 36.62205, -85.78853 36.621..."
3079,"{'lon': -86.87057234500053, 'lat': 36.52543835...",2022,[47],Tennessee,[47147],[Robertson],USA,county,Robertson County,147,01639786,"POLYGON ((-86.56391 36.63356, -86.56402 36.633..."
3112,"{'lon': -82.30414228084246, 'lat': 36.51291550...",2022,[47],Tennessee,[47163],[Sullivan],USA,county,Sullivan County,163,01639793,"POLYGON ((-82.68068 36.43180, -82.68038 36.432..."
3180,"{'lon': -87.03477760140554, 'lat': 35.20215093...",2022,[47],Tennessee,[47055],[Giles],USA,county,Giles County,055,01639746,"POLYGON ((-87.22405 34.99938, -87.22357 34.999..."
3181,"{'lon': -88.1844852516012, 'lat': 35.198676203...",2022,[47],Tennessee,[47071],[Hardin],USA,county,Hardin County,071,01639751,"POLYGON ((-88.36353 34.99547, -88.35890 34.995..."

In [19]:
dist_scores_percent = pd.read_csv('../data/dist_scores_percent.csv')
dist_scores_percent

,Unnamed: 0.1,Unnamed: 0,district,system,subject,pct_below,pct_approaching,pct_met_expectations,pct_exceeded_expectations,pct_met_exceeded,County Number,County Name,District Number
0,0,491,Anderson County,10,ELA,27.2,43,24,5.8,29.8,1,Anderson County,10
1,1,931,Anderson County,10,Math,34.9,37,21.5,6.6,28.2,1,Anderson County,10
2,2,1452,Clinton,11,ELA,15.3,35,33.6,16.1,49.7,1,Anderson County,11
3,3,1565,Clinton,11,Math,18.7,32.5,36.6,12.2,48.8,1,Anderson County,11
4,4,2259,Oak Ridge,12,ELA,16.9,39.7,32.3,11.1,43.5,1,Anderson County,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,277,161560,Wilson County,950,Math,16.5,31.3,35.4,16.8,52.2,189,Wilson County,950
278,278,162231,Lebanon,951,ELA,25.8,41.3,26.4,6.5,32.9,189,Wilson County,951
279,279,162516,Lebanon,951,Math,27.5,36.6,28.6,7.3,35.8,189,Wilson County,951
280,280,165618,Achievement School District,985,ELA,56.1,35.2,7.7,1,8.8,157,Shelby County,985
281,281,166107,Achievement School District,985,Math,**,**,**,**,6.1,157,Shelby County,985

In [21]:
dist_scores_percent = pd.merge(dist_scores_percent, tn_counties, left_on = 'County Name', right_on = 'coty_name_long', how = 'inner')
dist_scores_percent

,Unnamed: 0.1,Unnamed: 0,district,system,subject,pct_below,pct_approaching,pct_met_expectations,pct_exceeded_expectations,pct_met_exceeded,...,ste_code,ste_name,coty_code,coty_name,coty_area_code,coty_type,coty_name_long,coty_fp_code,coty_gnis_code,geometry
0,0,491,Anderson County,10,ELA,27.2,43,24,5.8,29.8,...,[47],Tennessee,[47001],[Anderson],USA,county,Anderson County,001,01639722,"POLYGON ((-84.00432 36.27038, -84.01092 36.272..."
1,1,931,Anderson County,10,Math,34.9,37,21.5,6.6,28.2,...,[47],Tennessee,[47001],[Anderson],USA,county,Anderson County,001,01639722,"POLYGON ((-84.00432 36.27038, -84.01092 36.272..."
2,2,1452,Clinton,11,ELA,15.3,35,33.6,16.1,49.7,...,[47],Tennessee,[47001],[Anderson],USA,county,Anderson County,001,01639722,"POLYGON ((-84.00432 36.27038, -84.01092 36.272..."
3,3,1565,Clinton,11,Math,18.7,32.5,36.6,12.2,48.8,...,[47],Tennessee,[47001],[Anderson],USA,county,Anderson County,001,01639722,"POLYGON ((-84.00432 36.27038, -84.01092 36.272..."
4,4,2259,Oak Ridge,12,ELA,16.9,39.7,32.3,11.1,43.5,...,[47],Tennessee,[47001],[Anderson],USA,county,Anderson County,001,01639722,"POLYGON ((-84.00432 36.27038, -84.01092 36.272..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,275,160033,Franklin SSD,941,Math,18.5,30.7,33.1,17.7,50.8,...,[47],Tennessee,[47187],[Williamson],USA,county,Williamson County,187,01639801,"POLYGON ((-87.21510 35.85065, -87.21184 35.849..."
278,276,161002,Wilson County,950,ELA,14.7,36.8,35.7,12.8,48.5,...,[47],Tennessee,[47189],[Wilson],USA,county,Wilson County,189,01639802,"POLYGON ((-86.59436 36.24538, -86.59429 36.245..."
279,277,161560,Wilson County,950,Math,16.5,31.3,35.4,16.8,52.2,...,[47],Tennessee,[47189],[Wilson],USA,county,Wilson County,189,01639802,"POLYGON ((-86.59436 36.24538, -86.59429 36.245..."
280,278,162231,Lebanon,951,ELA,25.8,41.3,26.4,6.5,32.9,...,[47],Tennessee,[47189],[Wilson],USA,county,Wilson County,189,01639802,"POLYGON ((-86.59436 36.24538, -86.59429 36.245..."
281,279,162516,Lebanon,951,Math,27.5,36.6,28.6,7.3,35.8,...,[47],Tennessee,[47189],[Wilson],USA,county,Wilson County,189,01639802,"POLYGON ((-86.59436 36.24538, -86.59429 36.245..."